### ISSUE TITLE
Cannot save forms in v1.9.4 - POST error 400 - rest_invalid_param cf_edit_nonce

### ISSUE THREAD

**Issue by filak** [CalderaWP/Caldera-Forms#3681]
## Do You Need Immediate Help?
* YES

## Is This A Feature Request?
* NO

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
* WordPress Version: 5.6.2 PHP Version: 7.4.11 MySQL Version: 8.0.22 Caldera Forms Version: 1.9.4

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
* It seems irrelevant - I have tried in TwentyTwenty theme and it does not work either

## What Is The Unexpected Behaviour?
I am able to create a blank form BUT I cannot save any updates/edits.

I just click on the Save button - it goes "Saving" and switch back. 

I see some warnings and errors in Chrome debugger:
- warning in Console:  (This seems unrelated to the issue)
[DOM] Found 2 elements with non-unique id #caldera-forms-custom_callback

- error in Network tab:
https://.../wp-json/cf-api/v2/forms/CF60 ... ?_locale=user - POST error 400 - rest_invalid_param cf_edit_nonce

```
    code: "rest_invalid_param"
    data:
    params: {cf_edit_nonce: "cf_edit_nonce není typu string."}
    cf_edit_nonce: "cf_edit_nonce is not type of [translated] string."
    status: 400
    message: "Invalid parameter: cf_edit_nonce"
```

## What PHP Errors Have You Logged While Reproducing This Bug?
* None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* None
